server {
    server_name kelvinmcmillan.art www.kelvinmcmillan.art;

    root /var/www/kelvin-mcmillan-art-web/dist;
    index index.html;
    client_max_body_size 10M;

    include /etc/nginx/sites-available/backend-locations.conf;

    location / {
        try_files $uri /index.html;
    }

    listen 443 ssl; 
    ssl_certificate /etc/letsencrypt/live/kelvinmcmillan.art/fullchain.pem; 
    ssl_certificate_key /etc/letsencrypt/live/kelvinmcmillan.art/privkey.pem; 
    include /etc/letsencrypt/options-ssl-nginx.conf; 
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 
}

server {
    listen 80;
    server_name kelvinmcmillan.art www.kelvinmcmillan.art;
    return 301 https://$host$request_uri;
}