server {
    listen 80;
    server_name _;

    root /var/www/kelvin-mcmillan-art-web/dist;
    index index.html;

     # Include backend API routes
    include /etc/nginx/sites-available/backend-locations.conf;

    # Frontend routes (must come after backend routes)
    location / {
        try_files $uri /index.html;
    }

    location ~ /\. {
        deny all;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}