name: Deploy React App to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
       VITE_API_URL: ${{ secrets.VITE_API_URL }}
       VITE_IMAGE_BASE_PATH: ${{ secrets.VITE_IMAGE_BASE_PATH}}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm, dependencies & build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_IMAGE_BASE_PATH: ${{ secrets.VITE_IMAGE_BASE_PATH }}

      - name: Copy build build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/kelvin-mcmillan-art-web/"

      - name: Copy nginx config
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "deploy/nginx.conf"
          target: "/etc/nginx/sites-available/kelvin-mcmillan-art-web"

      - name: Enable and reload nginx
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo ln -sf /etc/nginx/sites-available/kelvin-mcmillan-art-web /etc/nginx/sites-enabled/
            sudo nginx -t
            sudo systemctl reload nginx
